export default{
    name:'product',
    title:'product',
    type:'document',
    fields:[
        {
            name:'image',
            title:'Image',
            type:'array',
            of:[{type:'image'}],
            Options:{
                hotspot: true,
            }
        },
        {
            name:'name',
            title:'Name',
            type:'string',
        },
        {
            name:'slug',
            title:'slug',
            type:'slug',
            Options:{
                source:'name',
                maxLength:90,
            }
        },
        {
            name:'price',
            title:'Price',
            type:'number',

        },
        {
            name:'details',
            title:'Details',
            type:'string',
        }
    ]
}